"""new changes

Revision ID: 3f84570ebada
Revises: ccdb4f7ee44f
Create Date: 2022-05-08 07:37:32.263719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f84570ebada'
down_revision = 'ccdb4f7ee44f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###
    pass
