"""Create Book Table

Revision ID: 81ed18acc6ae
Revises: 
Create Date: 2022-05-07 17:15:00.543457

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81ed18acc6ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, unique = True),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('times_issued', sa.Integer(), nullable=False, default= 0 ),
    sa.PrimaryKeyConstraint('id'),
    
    )
    # ### end Alembic commands ###
    # op.execute("UPDATE books SET times_issued = 0")
    # op.alter_column('books', 'times_issued', nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
