"""Create Inventory Table

Revision ID: ae0d0173d3c2
Revises: b0de4c12170e
Create Date: 2022-05-07 17:16:58.634542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae0d0173d3c2'
down_revision = 'b0de4c12170e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False,default = 0),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    # ### end Alembic commands ###
