"""Create Relationship Added

Revision ID: ccdb4f7ee44f
Revises: f1502aa86058
Create Date: 2022-05-08 05:48:18.818546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccdb4f7ee44f'
down_revision = 'f1502aa86058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
